#!/usr/bin/env python3
"""Generate main/font16.h: a 16px bitmap font (printable ASCII 32..126) baked from a TTF
with no anti-aliasing (fontmode "1"), one uint16_t per row, bit0 = leftmost (same convention
as font8x8.h). Monospace cell so the C blitter stays as simple as fb_text. Build artifact,
not committed -- the build wrapper runs this alongside gen_screens.py / gen_render.py.

Font: PixelOperator-Bold.ttf (CC0 1.0, screens-src/fonts/) -- air-gap clean, already used @16."""
import os
from PIL import Image, ImageDraw, ImageFont

HERE = os.path.dirname(__file__)
TTF  = os.path.join(HERE, "..", "screens-src", "fonts", "po", "PixelOperator-Bold.ttf")
OUT  = os.path.join(HERE, "..", "main", "font16.h")
SIZE = 16
LO, HI = 32, 126

font = ImageFont.truetype(TTF, SIZE)
asc, desc = font.getmetrics()
CELL_H = min(asc + desc, 16)                                  # 16 rows max (uint16_t[16])
CELL_W = max(int(round(font.getlength(chr(c)))) for c in range(LO, HI + 1))
CELL_W = min(CELL_W, 16)                                       # 16 cols max (one uint16_t/row)

def glyph_rows(ch):
    img = Image.new("L", (CELL_W, CELL_H), 0)
    d = ImageDraw.Draw(img); d.fontmode = "1"                  # no anti-aliasing -> crisp 1-bit
    d.text((0, 0), ch, font=font, fill=255)
    px = img.load()
    rows = []
    for y in range(CELL_H):
        bits = 0
        for x in range(CELL_W):
            if px[x, y] >= 128:
                bits |= (1 << x)                               # bit0 = leftmost
        rows.append(bits)
    return rows

out = ["#pragma once",
       "/* generated by host/gen_font16.py from PixelOperator-Bold.ttf (CC0) -- do not edit here */",
       f"#define FONT16_W  {CELL_W}",
       f"#define FONT16_H  {CELL_H}",
       f"#define FONT16_LO {LO}",
       f"#define FONT16_HI {HI}",
       f"static const unsigned short font16[{HI - LO + 1}][{CELL_H}] = {{"]
for cp in range(LO, HI + 1):
    rows = glyph_rows(chr(cp))
    out.append("  {" + ",".join(f"0x{r:04x}" for r in rows) + f"}},  /* {cp} */")
out.append("};")
open(OUT, "w").write("\n".join(out) + "\n")
print(f"wrote {os.path.relpath(OUT)}: {HI - LO + 1} glyphs, cell {CELL_W}x{CELL_H} (asc={asc} desc={desc})")
